on: [push]

jobs:
  grumpy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Grumpy checks
        uses: jamieRowen/grumpy-actions@main
      - name: Run checks
        working-directory: "./python_pkgs/jrtimeman"
        run: grumpy about everything

