name: Publish

on:
  create:
    tags:
      - "v*.*.*"

jobs:
  publish-package:

    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Authenticate against pypi
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Build and publish
        working-directory: "./python_pkgs/jrtimeman"
        run: poetry publish --build
