name: Tag

on: 
  push: 
    branches: release-action

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.8

      - name: Get package version from pyproject.toml
        working-directory: "./python_pkgs/jrtimeman"
        run: echo "::set-output name=VERSION::$(poetry version --short)"
        id: package
      - name: Get git tags
        run: echo "::set-output name=TAGS::$(git --no-pager tag --list)"
        id: git

      - name: Display discovered package version
        run: echo ${{ steps.package.outputs.VERSION }}
      - name: Display discovered git tags
        run: echo ${{ steps.git.outputs.TAGS }}

      - name: Check if tag exists for current package version
        run: |
          echo "::set-output name=IS_TAGGED::$(echo ${{ steps.git.outputs.TAGS }} | grep -q ${{ steps.package.outputs.VERSION }})"
        id: version

      - name: Tag repo at discovered package version
        if: ${{ !steps.version.outputs.IS_TAGGED }}
        run: git tag -a v${{ steps.package.outputs.VERSION }} -m "v${{ steps.package.outputs.VERSION }} [CI-tagged]"
