name: Tag

on:
  workflow_run:
    workflows: ["verify"]
    branches: [release-action]
    types: [completed]

jobs:
  tag:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == "success" }}

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.8

      - name: Get package version from pyproject.toml
        working-directory: "./python_pkgs/jrtimeman"
        run: echo "::set-output name=VERSION::$(poetry version --short)"
        id: package
      - name: Get git tags
        run: echo "::set-output name=TAGS::$(git --no-pager tag --list)"
        id: git

      - name: Display discovered package version
        run: echo ${{ steps.package.outputs.VERSION }}
      - name: Display discovered git tags
        run: echo ${{ steps.git.outputs.TAGS }}

      - name: Check if tag exists for current package version
        run: |
          echo "::set-output name=IS_TAGGED::$(echo ${{ steps.git.outputs.TAGS }} | grep -q ${{ steps.package.outputs.VERSION }})"
        id: version

      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)

      - name: Tag repo at discovered package version
        if: ${{ !steps.version.outputs.IS_TAGGED }}
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.package.outputs.VERSION }}",
              sha: context.sha
            })
